
spring:
  datasource:
    username: seconddbadmin
    password: seconddbadmin
    url: jdbc:postgresql://localhost:5432/second_education
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
  main:
    banner-mode: OFF
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

jwt:
  secret: '[0-9.a-zA-z_]^+$TutorAcademy9891212skidU3AkjbgcNftrFbsdrxh^56409unjbgGfd528482'

file:
  storage:
    location: /home/software/fileStorage
server:
  port: 8081
  servlet:
    context-path: /
  ssl:
    enabled: true
    key-alias: qabul
    key-store: classpath:qabul.p12
    key-store-type: PKCS12
    key-password: qabulkey
    key-store-password: qabulkey